version: '3'
services:
    api:
      container_name: 'go_test_docker'
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
        - "80:80"
      volumes:
          - ./:/go/src/app/
          - ./go.mod:/go/src/app/go.mod
      restart: always
